source 'https://github.com/CocoaPods/Specs.git'

pod 'AWSCore'
#pod 'AWSAutoScaling'
#pod 'AWSLambda'
#pod 'AWSMachineLearning'
#pod 'AWSMobileAnalytics'
pod 'AWSS3'
pod 'AWSSimpleDB'
#pod 'AWSSNS'
#pod 'AWSSQS'
#pod 'AWSCognito'

#pod 'iOS-Slide-Menu'
pod 'CHCSVParser'
